sudo: required
language: python
services:
  - docker
install:
  - make docker-build
script:
  - docker run --rm -it sbastkowski/albatradis:dev /bin/sh -c "cd /albatradis && make test"
deploy:
  skip_cleanup: true
  provider: script
  script: make docker-push
  on:
    tags: true
    branch: master
