sudo: required
services:
  - docker
install:
  - docker pull quadraminstitute/albatradis
script:
  - docker run --rm -it quadraminstitute/albatradis /bin/sh -c "git clone https://github.com/quadram-institute-bioscience/albatradis.git && cd albatradis && python3 setup.py test"