#!/usr/bin/env python3

import argparse
import sys
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from tradistron.TradisTron import TradisTron


version = ''
try:
	version = pkg_resources.get_distribution("tradistron").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'Tradis analysis',
	usage = 'tradistron [options] plotfiles', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('plotfiles', help='Input plot files (optionally gzipped)', nargs='+', type=str)

parser.add_argument('--minimum_threshold', '-m', help='Only include insert sites with this number or greater insertions', type=int, default=4)
parser.add_argument('--window_size',	 '-w', help='Window size', type=int, default= 100)
parser.add_argument('--window_interval', '-i',  help='Window interval', type=int, default=100)
parser.add_argument('--minimum_logfc', '-f',  help='Minimum log fold change', type=float, default=3.0)
parser.add_argument('--prefix', '-o',  help='Output filename prefix', type=str, default='tradistron')
parser.add_argument('--pvalue', '-p',  help='Dont report anything above this p-value', type=float, default=0.05)
parser.add_argument('--verbose', '-v', action='store_true', help='Turn on debugging [%(default)s]', default = False)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

tradistron = TradisTron(options)
tradistron.run()
